network:
  dest_ip: "192.168.10.100"
  top_view_port : 50000
  bottom_view_port : 50001

camera:
  top_view_device: "/dev/video2"
  bottom_view_device: "/dev/video0"
  width: 1280
  height: 960

image_processor:
  jpeg_quality: 90
  resize_width: 1280
