network:
  dest_ip: "192.168.76.209"
  top_view_port : 50000
  bottom_view_port : 50001

camera:
  top_view_device: "/dev/video0"
  bottom_view_device: "/dev/video2"
  width: 800
  height: 600

image_processor:
  jpeg_quality: 90
  resize_width: 640
